In [1]:
import pandas as pd
import numpy as np

In [32]:
"""
numpy.concatenate()
"""

x = [1,2,3]
y = [4,5,6]
z = [7,8,9]

print(np.concatenate([x,y,z])) # vstack(), hstack()
print(np.vstack([x,y,z]))

x = [[1, 2], # 2D array
     [3, 4]]

# axis=0(row-based), 1(column-based)
print(np.concatenate([x, x], axis=1))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 1 2]
 [3 4 3 4]]


In [8]:
"""
pandas.concat()
"""

# Simply concatenate the two Series objects

ser1 = pd.Series(['A', 'B', 'C'], index=[1,2,3])
ser2 = pd.Series(['D', 'E', 'F'], index=[4,5,6])
print(ser1)
print(ser2, '\n\n')

print(pd.concat([ser1, ser2]))

1    A
2    B
3    C
dtype: object
4    D
5    E
6    F
dtype: object 


1    A
2    B
3    C
4    D
5    E
6    F
dtype: object


In [10]:
# make_df() : create a DataFrame object
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
           for c in cols}

    return pd.DataFrame(data, ind)

print(make_df('ABC', [1,2]))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2


In [12]:
# Concatenate the two DataFrame objects
df1 = make_df('AB', [1,2])
df2 = make_df('AB', [3,4])

print(pd.concat([df1, df2]))

    A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4


In [15]:
df3 = make_df('AB', [0, 1])
df4 = make_df('CD', [0, 1])

print(pd.concat([df3, df4], axis=1))

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1


In [34]:
"""
    concate() Features
"""

# Case 1: Duplicate indices

x = make_df('AB', [0, 1])
y = make_df('AB', [2, 3])

y.index = x.index # make duplicate indices

print(pd.concat([x, y]))

    A   B
0  A0  B0
1  A1  B1
0  A2  B2
1  A3  B3


In [35]:
# Case 2: Catching duplications as errors

try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError: ", e)

ValueError:  Indexes have overlapping values: Int64Index([0, 1], dtype='int64')


In [37]:
# Case 3: Ignore the index:
# assign integer-based indices automatically

print(pd.concat([x, y], ignore_index=True))

# Case 4: Adding multiindex keys (hierarchical indexing)

print(pd.concat([x, y], keys=['x', 'y']))

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
      A   B
x 0  A0  B0
  1  A1  B1
y 0  A2  B2
  1  A3  B3


In [38]:
"""
    concat(): join options
"""

x = make_df('ABC', [1, 2])
y = make_df('BCD', [3, 4])

print(x, '\n')
print(y, '\n')
print(pd.concat([x, y], join='outer')) # union

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4


In [40]:
# inner join -> intersection

print(x, '\n')
print(y, '\n')
print(pd.concat([x, y], join='inner'))

    A   B   C
1  A1  B1  C1
2  A2  B2  C2 

    B   C   D
3  B3  C3  D3
4  B4  C4  D4 

    B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4


In [42]:
# append()

print(df1);
print(df2); 
print(df1.append(df2))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25
  employee  hire_date  age
0     Lisa       2004   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25
  employee        group  age  hire_date
0      Bob   Accounting   20        NaN
1     Jake  Engineering   42        NaN
2     Lisa  Engineering   37        NaN
3      Sue           HR   25        NaN
0     Lisa          NaN   37     2004.0
1      Bob          NaN   20     2008.0
2     Jake          NaN   42     2012.0
3      Sue          NaN   25     2014.0


In [17]:
"""
join operations
"""

df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'group': ['Accounting', 'Engineering', 'Engineering', 'HR']})

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                   'hire_date': [2004, 2008, 2012, 2014]})


In [43]:
# One to one joins

df3 = pd.merge(df1, df2)
print(df3)

  employee        group  age  hire_date
0      Bob   Accounting   20       2008
1     Jake  Engineering   42       2012
2     Lisa  Engineering   37       2004
3      Sue           HR   25       2014


In [44]:
# Many-to-one joins

df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                   'supervisor': ['Carly', 'Guido', 'Steve']})

print(df3, '\n')
print(df4, '\n')

print(pd.merge(df3, df4))

  employee        group  age  hire_date
0      Bob   Accounting   20       2008
1     Jake  Engineering   42       2012
2     Lisa  Engineering   37       2004
3      Sue           HR   25       2014 

         group supervisor
0   Accounting      Carly
1  Engineering      Guido
2           HR      Steve 

  employee        group  age  hire_date supervisor
0      Bob   Accounting   20       2008      Carly
1     Jake  Engineering   42       2012      Guido
2     Lisa  Engineering   37       2004      Guido
3      Sue           HR   25       2014      Steve


In [45]:
# Many-to-many joins

df5 = pd.DataFrame({'group': ['Accounting', 'Accounting',
                             'Engineering', 'Engineering',
                             'HR', 'HR'],
                   'skills': ['math', 'spreadsheets', 'coding',
                             'linux', 'spreadsheets', 'organization']})

print(df1, '\n')
print(df5, '\n')

print(pd.merge(df1, df5))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization 

  employee        group  age        skills
0      Bob   Accounting   20          math
1      Bob   Accounting   20  spreadsheets
2     Jake  Engineering   42        coding
3     Jake  Engineering   42         linux
4     Lisa  Engineering   37        coding
5     Lisa  Engineering   37         linux
6      Sue           HR   25  spreadsheets
7      Sue           HR   25  organization


In [46]:
"""
Specify the merge Key
"""

# 'on' argument : use a common column as merge key
df1['age'] = pd.Series([20,42,37,25])
df2['age'] = pd.Series([37,20,42,25])

print(df1, '\n')
print(df2)

print(pd.merge(df1, df2, on='employee'), '\n')

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

  employee  hire_date  age
0     Lisa       2004   37
1      Bob       2008   20
2     Jake       2012   42
3      Sue       2014   25
  employee        group  age_x  hire_date  age_y
0      Bob   Accounting     20       2008     20
1     Jake  Engineering     42       2012     42
2     Lisa  Engineering     37       2004     37
3      Sue           HR     25       2014     25 



In [26]:
# 'left_on' and 'right_on' arguments:

df3 = pd.DataFrame({'name' : ['Bob', 'Jake', 'Lisa', 'Sue'],
                   'salary' : [70000, 80000, 120000, 90000]})

print(df1, '\n')
print(df3, '\n')

print(pd.merge(df1, df3, left_on='employee', right_on='name'))

  employee        group  age
0      Bob   Accounting   20
1     Jake  Engineering   42
2     Lisa  Engineering   37
3      Sue           HR   25 

   name  salary
0   Bob   70000
1  Jake   80000
2  Lisa  120000
3   Sue   90000 

  employee        group  age  name  salary
0      Bob   Accounting   20   Bob   70000
1     Jake  Engineering   42  Jake   80000
2     Lisa  Engineering   37  Lisa  120000
3      Sue           HR   25   Sue   90000


In [30]:
# 'left_index' and 'right_index' arguments
df1a = df1.set_index('employee')
df2a = df2.set_index('employee')

print(df1a)
print(df2a)

print(pd.merge(df1a, df2a, left_index=True, right_index=True))

                group  age
employee                  
Bob        Accounting   20
Jake      Engineering   42
Lisa      Engineering   37
Sue                HR   25
          hire_date  age
employee                
Lisa           2004   37
Bob            2008   20
Jake           2012   42
Sue            2014   25
                group  age_x  hire_date  age_y
employee                                      
Bob        Accounting     20       2008     20
Jake      Engineering     42       2012     42
Lisa      Engineering     37       2004     37
Sue                HR     25       2014     25


In [48]:
"""
    Specifying the Join method
"""

df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                   'food': ['fish', 'beans', 'bread']},
                  columns=['name', 'food'])

df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                   'drink': ['wine', 'beer']},
                  columns=['name', 'drink'])

print(df6, '\n')
print(df7)

# inner join (default)

print(pd.merge(df6, df7, how='inner'))

# outer join

print(pd.merge(df6, df7, how='outer'))

# left join

print(pd.merge(df6, df7, how='left'))

# right join

print(pd.merge(df6, df7, how='right'))

    name   food
0  Peter   fish
1   Paul  beans
2   Mary  bread 

     name drink
0    Mary  wine
1  Joseph  beer
   name   food drink
0  Mary  bread  wine
     name   food drink
0   Peter   fish   NaN
1    Paul  beans   NaN
2    Mary  bread  wine
3  Joseph    NaN  beer
    name   food drink
0  Peter   fish   NaN
1   Paul  beans   NaN
2   Mary  bread  wine
     name   food drink
0    Mary  bread  wine
1  Joseph    NaN  beer
